spring:
  application:
    name: user-service

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: user
    password: pw
    schema: public
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update

server:
    port: 8081
    servlet:
      context-path: /user-service



#Remove below to disable structured JSON logging
#logging:
#  structured:
#    format:
#      console: ecs

multitenancy:
  http:
    header-name: X-TenantId
  tenants:
    localhost:
      datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        schema: public
        username: user
        password: pw
        driver-class-name: "org.postgresql.Driver"



logging.level.com.arfat: DEBUG
logging.level.org.hibernate.SQL: DEBUG
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.type.descriptor.sql: trace